#!/bin/sh

# Load Xresources if present
xres="$XDG_CONFIG_HOME/xorg.d/Xresources"
[ -f "$xres" ] && xrdb "$xres"

# Launch dbus for current user session
killall dbus-daemon
eval $(dbus-launch --sh-syntax)

# Set cursor to something good
xsetroot -cursor_name left_ptr

# Solid background
hsetroot -solid '#414A4C'

# Compositor
picom -b --config "$XDG_CONFIG_HOME/picom/picom.conf"

# Colemak TODO: set this in X config instead
setxkbmap -layout us colemak

# Notifications
dunst &

# Starting low battery notifications daemon
lowbatteryd "$LOWBATTERYD_INTERVAL" "$BATTERY_CRITICAL" &

# Starting the wm
sxhkd -m 1 &
exec "$WM"
