#!/bin/sh

userresources=$XDG_CONFIG_HOME/xorg.d/Xresources
sysresources=/etc/X11/xinit/.Xresources

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

export LANG=en_US.UTF-8

[ -f "$HOME/.profile" ] && . "$HOME/.profile"

pulseaudio -D

redshift -t 6500:3900 & #

wal -st -n -R
# xwallpaper --zoom "$(cat $WALL)"
xsetroot -grey

# picom -b

xsetroot -cursor_name left_ptr

setxkbmap -layout us colemak
sxhkd -m 1 &

rm /tmp/lockp
xss-lock $BIN/x/lockscreen &

dunst &

sleep 0.4
lowbatteryd "$LOWBATTERYD_INTERVAL" "$BATTERY_CRITICAL"

#mkdir -p $HOME/fs
exec "$WM"
#initwm
#exec evd

#x11fs "$HOME/fs"
#bash -c 'sleep infinity'
#fusermount -u "$HOME/fs"

