. $HOME/.profile

xset r rate 200 50
resources=$XDG_CONFIG_HOME/xorg.d/Xresources

if [ -f "$resources" ]; then
	xrdb -load "$resources"
fi

# hsetroot -solid '#434343' &
hsetroot -fill "$WALL" &

"$WM"
