#!/bin/sh

alias a=alias

a doas="doas --"

a ls="ls -a --group-directories-first --color"
a ll="ls -l"
a rr="rm -Rf"
a c=clear
a wd=smartpath

a p=echo

a gall="git add -A"
a gcm="git commit -m"
a gs="git status"

a scan="doas iwd -d 2>&1 | grep -i 'new network' ; doas iwd &"

a r=ranger

a v=nvim
a dv="doas nvim"

weather() {
	loc="$1"
	[ -z "$loc" ] && loc='?m' ; curl "https://wttr.in/$loc"
}

toclip() {
	cat "$1" | xclip -sel clip -i
}

a fetch=neofetch

a pkg="doas pkg"

. "$XDG_CONFIG_HOME/home.d/landmarks"
