#!/bin/sh

while read -r lbl dest; do
	a "g$lbl"="cd $dest"
done <<EOF
H $HOME
B $HOME/bin
E $HOME/etc
S $HOME/usr/src
s $HOME/usr/local/share
O $HOME/opt
W $HOME/med/wall
D $HOME/med/doc
d $HOME/usr/doc
M $HOME/med
w $HOME/bin/wrap
x $HOME/bin/x
X $HOME/etc/xorg.d
h $HOME/etc/home.d
mn /mnt
EOF
