#!/bin/sh

while read -r al; do
	a g${al% *}="cd ${al#* }"
done <<EOF
H "$HOME"
B "$HOME/bin"
E "$HOME/etc"
S "$HOME/usr/src"
R "$HOME/opt"
W "$HOME/med/wall"
D "$HOME/med/doc"
d "$HOME/usr/doc"
M "$HOME/med"
Z "$HOME/etc/zsh"
w "$HOME/bin/wrap"
m /mnt
EOF
