#!/bin/bash

killall admiral

admiral | lemonbar -g x22 -f "$(xrdb-get bspwm font)" -f "Font Awesome 5 Free:style=Solid:pixelsize=12:antialiasing=true:hinting=true" -a 15 -B $(xrdb-get bspwm color2) -F $(xrdb-get bspwm color1) | sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color $(xrdb-get bspwm color8)
bspc config focused_border_color $(xrdb-get bspwm color10)

bspc config border_width 		2
bspc config window_gap 			2

bspc config split_ratio 		0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config single_monocle 		true
bspc config focus_follows_pointer	false

#######
# Rules
#######

bspc rule -a St state=pseudo_tiled center=true rectangle=640x400+0+0
bspc rule -a Zathura state=pseudo_tiled

xdo above -t $(xdo id -n root) $(xdo id -n lemonbar)
