#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config normal_border_color $(xrdb-get bspwm color6)
#bspc config focused_border_color $(xrdb-get bspwm color6)

bspc config border_width 		0
bspc config window_gap 			2

bspc config split_ratio 		0.50
bspc config borderless_monocle		false
bspc config gapless_monocle		true
bspc config single_monocle 		true
bspc config focus_follows_pointer	true

#######
# Rules
#######

bspc rule -a notif state=floating sticky=true
bspc rule -a St state=pseudo_tiled center=true rectangle=1500x875+0+0
bspc rule -a Zathura state=floating rectangle=700x1000+0+0 center=true

##########
# Metadata
##########

# atomx _NEW_WM_NAME=bsp 0x01000000
# xprop -id 0x1000000 -notype -f _NET_WM_NAME 8s -set _NET_WM_NAME "bsp"
