#!/bin/bash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color $(xrdb-get bspwm color8)
bspc config focused_border_color $(xrdb-get bspwm color7)

bspc config border_width 		1
bspc config window_gap 			2

bspc config split_ratio 		0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config single_monocle 		true
bspc config focus_follows_pointer	false

#######
# Rules
#######

bspc rule -a St state=pseudo_tiled center=true rectangle=1500x875+0+0
bspc rule -a Zathura state=pseudo_tiled
